### ISSUE TITLE
issue with .. in app.py

### ISSUE THREAD

**Issue by risayew** [techcto/S3initRKE#1]
https://github.com/techcto/rke-runner/blob/e4a6acc950cd2f668a2e959f1b6923de52c45eda/app.py#L101

Was it added occasionally?

**Comment by techcto** [comment]
Sorry about that. It was typo.  I got really far with this, but had to pause for other projects.  I just pushed, please let me know if you have interest in this.

**Comment by risayew** [comment]
Thank you very much! I have started with rancher 1.6 on custom host, collected some experience with rancher 1.6. And now i want to try out rancher 2.0 on aws cloud. So, i am interested in your project. May be i can participate in the project somehow?
