### ISSUE TITLE
Failed to provision volume with StorageClass “my-storage”: Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead

### ISSUE THREAD

**Issue by risayew** [techcto/S3initRKE#3]
I have imported already existing cluster to rancher, and have the following problem, if i try to create storage class and use it in workload. I'm not sure, that this issue is related to this repo.

**Comment by techcto** [comment]
Sounds like a rancher thing. This repo just installs and tries to keep load balancer updated if a node goes down.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by risayew** [comment]
solved, was problem in rancher
